config/routes.rb
Monica::Application.routes.draw do

  resources :articles

  root :to => "homes#index"
  resources :reports
  match "about" => "articles#about"
  match "contacts" => "articles#contact"
  
  resources :reports do
    member do
      post :vote_up
    end
  end
  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}
  match "/auth/:provider/callback" => "authentications#create"

end

app/models/report.rb
class Report < ActiveRecord::Base
  acts_as_voteable
  belongs_to :category
  belongs_to :user
  belongs_to :state
  has_many :comments

  accepts_nested_attributes_for :user
  accepts_nested_attributes_for :comments
  accepts_nested_attributes_for :state
  validates_presence_of :user
  validates_presence_of :category_id
  validates_presence_of :subject
  validates_presence_of :description

  time = Time.new
  scope :approved, where(:approved => true)
  scope :jan, lambda { {:conditions => ['created_at > ? AND created_at < ?', Date.parse(time.year.to_s+'-01-01'), Date.parse(time.year.to_s+'-01-31')]} }
  scope :feb, lambda { {:conditions => ['created_at > ? AND created_at < ?', Date.parse(time.year.to_s+'-02-01'), Date.parse(time.year.to_s+'-01-29')]} }
  scope :mar, lambda { {:conditions => ['created_at > ? AND created_at < ?', Date.parse(time.year.to_s+'-03-01'), Date.parse(time.year.to_s+'-03-31')]} }
  scope :apr, lambda { {:conditions => ['created_at > ? AND created_at < ?', Date.parse(time.year.to_s+'-04-01'), Date.parse(time.year.to_s+'-04-30')]} }
  scope :may, lambda { {:conditions => ['created_at > ? AND created_at < ?', Date.parse(time.year.to_s+'-05-01'), Date.parse(time.year.to_s+'-05-31')]} }
  scope :jun, lambda { {:conditions => ['created_at > ? AND created_at < ?', Date.parse(time.year.to_s+'-06-01'), Date.parse(time.year.to_s+'-06-30')]} }
  scope :jul, lambda { {:conditions => ['created_at > ? AND created_at < ?', Date.parse(time.year.to_s+'-07-01'), Date.parse(time.year.to_s+'-07-31')]} }
  scope :aug, lambda { {:conditions => ['created_at > ? AND created_at < ?', Date.parse(time.year.to_s+'-08-01'), Date.parse(time.year.to_s+'-08-31')]} }
  scope :sep, lambda { {:conditions => ['created_at > ? AND created_at < ?', Date.parse(time.year.to_s+'-09-01'), Date.parse(time.year.to_s+'-09-30')]} }
  scope :oct, lambda { {:conditions => ['created_at > ? AND created_at < ?', Date.parse(time.year.to_s+'-10-01'), Date.parse(time.year.to_s+'-10-31')]} }
  scope :nov, lambda { {:conditions => ['created_at > ? AND created_at < ?', Date.parse(time.year.to_s+'-11-01'), Date.parse(time.year.to_s+'-11-30')]} }
  scope :dec, lambda { {:conditions => ['created_at > ? AND created_at < ?', Date.parse(time.year.to_s+'-12-01'), Date.parse(time.year.to_s+'-12-31')]} }

  #attached photo using paperclip
  #has_attached_file :photo, :styles => {:medium => "306x238>"}
  #validates_attachment_content_type :photo, :content_type => ['image/jpeg']

  has_many :assets, :dependent => :destroy
  accepts_nested_attributes_for :assets

  def self.total_on(date)
    where("date(created_at) = ?", date).count()
  end

  def self.total_month()
#  Article.count(:group=>"DATE_FORMAT(created_at, '%Y %b')")
    Report.count(:group=>"DATE_FORMAT(created_at, '%Y %b')")
#  where("date(created_at) = ?", datas).count()
  end

#  where("date(created_at) = ?", datas).count()


  def self.get_problem_count(state_id, is_solved)
    Report.where(:state_id => state_id, :solved => is_solved).count
  end
end

app/controllers/reports_controller.rb
# encoding: utf-8
# encoding: utf-8
class ReportsController < ApplicationController

    #uses_tiny_mce :options => {
     # :theme => 'advanced',
      #:theme_advanced_resizing => true,
      #:theme_advanced_toolbar_location => "top",
      #:theme_advanced_toolbar_align => "left",
      #:theme_advanced_resize_horizontal => false,
      #:theme_advanced_buttons1 => %w{formatselect bold italic underline strikethrough separator justifyleft justifycenter justifyright indent separator bullist numlist separator forecolor backcolor separator link unlink separator undo redo},
      #:theme_advanced_buttons2 => [],
      #:theme_advanced_buttons3 => [],
      #:width => 200,
      #:theme_advanced_disable => "help,cleanup,charmap,sub,sup,visualaid,anchor,image,code",
      #:plugins => %w{ table fullscreen }
    #}

  before_filter :authorize, :except => [:index, :new, :show, :create, :destroy, :vote_up]

  def index
    @article = Article
    sleep 2
    @reports = Report.approved.order("created_at desc").paginate(:per_page => 5, :page => params[:page])
    #@comments = Comment.find(:all, :order => 'comments.created_at DESC', :limit=> 5)
    respond_to do |format|
      format.js
      format.html
    end
  end

  def show
    begin
      @reports = Report.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Такой страницы не существует!"
      redirect_to reports_path, :notice => "Такой страницы не существует!"
    else
      respond_to do |format|
        format.html
      end
    end

  end

  def new
    @reports = Report.new
    3.times { @reports.assets.build }
    unless current_user
      @reports.user = User.new
    end
    respond_to do |format|
      format.html # index.html.erb
      format.js
    end

  end

  def create
    @reports = Report.new(params[:report])
    if current_user
      @reports.user_id = current_user.id
    end
    if @reports.save
      flash[:notice] = t('general.created')
      redirect_to @reports
    else
      if (@reports.errors['user.email'] == ["Такой email уже существует"] || @reports.errors['user.email'] == ["has already been taken"]) && (@reports.errors.count <= 1)
        @reports.save(:validate => false)
        flash[:notice] = t('general.created')
        redirect_to @reports
      else
        render :action => 'new'
      end
    end
  end

  def edit
    @reports = Report.find(params[:id])
    3.times { @reports.assets.build }
  end

  def update
    @reports = Report.find(params[:id])
    if @reports.update_attributes(params[:report])
      flash[:notice] = t('general.updated')
      redirect_to reports_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @reports = Report.find(params[:id])
    @reports.destroy
    flash[:notice] = t('general.destroyed')
    redirect_to reports_url
  end

  def vote_up
    @reports = Report.find(params[:id])
    if user_signed_in?
      unless current_user.voted_for?(@reports)
        if current_user.vote_for(@reports)
          respond_to do |format|
            format.html
            format.js { redirect_to :action => 'show' }
          end
        end
      end
    else
      respond_to do |format|
        format.html
        format.js { redirect_to :action => 'show' }
      end
    end
  end


end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<!--pages title at top-->
<% @page_title = 'New report' %>

<% unless user_signed_in? %>
 <script type="text/javascript">
   $(document).ready(function() {
       $('#anonymous_user_fields').css('display', 'none');
       $('#anonymous_user_fields input#report_user_attributes_name').inputfocus({ value: 'Anonymous'});
       $('#anonymous_user_fields input#report_user_attributes_last_name').inputfocus({ value: 'Anonymous'});
       $('#anonymous_user_fields input#report_user_attributes_email').inputfocus({ value: 'anonymous@anonym.net'});
       $('#anonymous_user_fields input#report_user_attributes_phone').inputfocus({ value: '0312112233'});
   });
 </script>
<% end %>

<%= simple_form_for(@reports, :html => {:id => 'commentform', :multipart => true}) do |f| %>
  <% unless user_signed_in? %>
    <%= f.fields_for :user do |u| %>
      <div id="show_hide_link"><a href="#">Дополнительные данные</a></div>
      <div id="anonymous_user_fields">
        <%= u.input :name, :label => t('general.name'), :input_html => {:value => 'Anonymous'} %>
        <%= u.input :last_name, :label => t('general.last_name'), :input_html => {:value => 'Anonymous'} %>
        <%= u.input :email, :label => t('general.email'), :input_html => {:value => 'anonymous@anonym.net'} %>
        <%= u.input :phone, :label => t('general.phone'), :input_html => {:value => '0312112233'} %>
        <%= u.hidden_field :is_anonym, :value => true %>
      </div>
    <% end %>
  <% end %>
  <%= f.input :address, :label => 'address' %>
  <%= f.hidden_field :state_id, :label => 'state' %>
  <%= f.hidden_field :coordinates, :label => 'coordinates' %>
  <%= f.association :category, :label => t('general.category') %>
  <%= f.input :subject, :label => t('general.subject') %>
  <%= f.text_area :description %><br />

  <div id="tasks">
    <%= f.fields_for :assets do |asset| %>
      <% if asset.object.new_record? %>
        <br><br>
        <%= asset.file_field :image %>
      <% end %>
    <% end %>
  </div>
  <br>


  <%= f.button :submit, :value => t('general.report_button') %>
<% end %>

app/views/reports/_formEdit.html.erb
<!--pages title at top-->
<% @page_title = 'New report' %>

<%= simple_form_for(@reports, :html => {:id => 'commentform', :multipart => true}) do |f| %>
    <div style="float: right; vertical-align: top; margin-right: 20px; color: green;">
        <%= f.input :solved, :label => t('general.solved')  %>
        <%= f.input :approved, :label => t('general.approved')  %>
    </div>
    <%= f.input :address, :label => t('general.address') %>
    <%= f.hidden_field :state_id, :label => 'state' %>
    <%= f.hidden_field :coordinates, :label => 'coordinates' %>
    <%= f.association :category, :label => t('general.category') %>
    <%= f.input :subject, :label => t('general.subject') %>
    <%= f.text_area :description %>

    <div class="newPaperclipFiles">
      <%= f.fields_for :assets do |asset| %>
          <% if asset.object.new_record? %><br><br>
              <%= asset.file_field :image %>
          <% end %>
      <% end %>
    </div>
    <br>


    <%= f.button :submit, :value => t('general.update') %>

<% end %>

app/views/reports/_reports.html.erb
<% for reports in @reports %>
    <%= status_tag(reports.solved) %>
    <p>
      <strong><%= t('general.subject') %>:</strong>
      <%= reports.subject %>
    </p>
    <p>
      <strong><%= t('general.description') %></strong>
      <%= truncate(reports.description, :length => 200, :omission => "...").html_safe %>
    </p>
    <p>
      <strong><%= t('general.category') %></strong>
      <%= reports.category.name %>
    </p>
    <p>
      <strong><%= t('general.state') %></strong>
      <%= reports.address %>
    </p>
    <p>
      <%= link_to t('general.show'), reports %>
      <% if admin? %>
          <%= link_to t('general.edit'), edit_report_path(reports) %>
          <%= link_to t('general.destroy'), reports, :confirm => t('general.confirm'), :method => :delete %>
      <% end %>
    <hr>
    </p>
<% end %>
<%= will_paginate @reports %>

app/views/reports/create.js.erb
$(":input").not(":button, :submit, :reset, :hidden").each( function() {
    this.value = '';
});

app/views/reports/edit.html.erb
<% @page_title = 'Edit report' %>

<h3><%= t('general.edit') %></h3>

<%= render 'formEdit' %>

<p>
  <%= link_to t('general.edit'), @reports %> |
  <%= link_to t('general.view'), reports_path %>
</p>

app/views/reports/index.html.erb
<% @page_title = 'Reports list' %>

<div id="main" class='col-left box'>
  <h3><%= t('general.recent_reports') %></h3><br/>

  <% javascript 'application' %>
  <div id="reports">
    <%= render 'reports' %>
  </div>


</div>

<div id="sidebar" class="col-right">
  <div class="widget">
    <% if I18n.locale == :ru %>
        <h1>Последние новости</h1>
    <% else %>
        <h1>Соңку жаңылыктар</h1>
    <% end %>
    <% @articles = @article.order("created_at desc").limit(5) %>
    <% for articles in @articles %>
        <b><%= link_to articles.title, articles %></b><br>

        <p><%= truncate(articles.content, :length => 300, :omission => "...").html_safe %></p>
        <span class="date_main"><%= articles.created_at %></span><br><br>
    <% end %>
  </div>
  <div class='widget'>
    <h3>Последние комментарии</h3>
    <!--<%# @comments.each do |comment| %>-->
    <!--<div class="comments_show">-->
    <!--<span class="author_name"><%#= comment.author %></span>-->
    <!--<span class="author_created_comment"><%#= display_date(comment.created_at) %></span>          <br>-->
    <!--<span class="comment_content"><%#= comment.content %></span>-->
    <!---->
    <!--</div>-->
    <!--<br>-->
    <!--<%# end %>-->
    <%= raw disqus_recent_comments(:color => "blue", :hide_mods => false, :num_items => 5, :avatar_size => 24) %>
  </div>
</div>

app/views/reports/index.js.erb
$("#reports").html("<%= escape_javascript(render("reports")).html_safe %>");  

app/views/reports/new.html.erb
<script type="text/javascript">
  
  var bi_0 = <%= Report.get_problem_count(8, false) %>;
  var bi_1 = <%= Report.get_problem_count(8, true) %>;

  var co_0 = <%= Report.get_problem_count(1, false) %>;
  var co_1 = <%= Report.get_problem_count(1, true) %>;

  var oo_0 = <%= Report.get_problem_count(2, false) %>;
  var oo_1 = <%= Report.get_problem_count(2, true) %>;

  var bo_0 = <%= Report.get_problem_count(3, false) %>;
  var bo_1 = <%= Report.get_problem_count(3, true) %>;

  var jo_0 = <%= Report.get_problem_count(4, false) %>;
  var jo_1 = <%= Report.get_problem_count(4, true) %>;

  var to_0 = <%= Report.get_problem_count(5, false) %>;
  var to_1 = <%= Report.get_problem_count(5, true) %>;

  var io_0 = <%= Report.get_problem_count(6, false) %>;
  var io_1 = <%= Report.get_problem_count(6, true) %>;

  var no_0 = <%= Report.get_problem_count(7, false) %>;
  var no_1 = <%= Report.get_problem_count(7, true) %>;


//  $(function() {
//    $('#respond :input').attr('disabled', true);
//  });
    


</script>
<%= javascript_include_tag "http://maps.google.com/maps/api/js?sensor=false&language=ru", "gmap", "epoly3" %>

<% @page_title = 'New report' %>
<h3><%= t('general.report_new') %></h3><br/>

<div id="featured" class="col-full">
  <div id="loopedSlider">

    <div class="container" style="height: 470px; display: block;">
      <div class="map" id="report_map" style="height:450px;"></div>
    </div>

    <div class="fix"></div>

    <div class="slider-nav col-full">

      <ul class="pagination">
        <li><a href="javascript:void(0);" onclick="goto_state('bi');" rel="1">Бишкек</a></li>
        <li><a href="javascript:void(0);" onclick="goto_state('co');" rel="2">Чуй</a></li>
        <li><a href="javascript:void(0);" onclick="goto_state('oo');" rel="3">Ош</a></li>
        <li><a href="javascript:void(0);" onclick="goto_state('bo');" rel="4">Баткен</a></li>
        <li><a href="javascript:void(0);" onclick="goto_state('jo');" rel="5">Джалал-Абад</a></li>
        <li><a href="javascript:void(0);" onclick="goto_state('to');" rel="6">Талас</a></li>
        <li><a href="javascript:void(0);" onclick="goto_state('no');" rel="7">Нарын</a></li>
        <li><a href="javascript:void(0);" onclick="goto_state('io');" rel="8">Иссык-Куль</a></li>
      </ul>
    </div>
  </div>

</div>

<div id="content" class="col-full">
  <div id="main" class="col-left box hidden_report_form">
    <div class="post-2 page type-page hentry">
      <h2 class="title"><%= t('general.report_form') %></h2>

      <div class="entry">
        <h4 id="before-notice" style="color:red;">Выберите область и укажите место</h4>
      </div>

    </div>

    <div id="respond">
      <%= render 'form' %>
    </div>
  </div>
  <div id="sidebar" class="col-right">
    <div class="widget widget_pages">
      <h3>Инструкция</h3>
      <p>Для того чтобы сообщить о проблеме вам необходимо указать адрес на карте.</p>
      <p>Вы можете подкорректировать выбранный адресс вручную</p>
    </div>
  </div>
</div>

app/views/reports/show.html.erb
<%= javascript_include_tag 'easySlider1.5' %>

<% @page_title = 'Show report' %>

<div id="main" class='col-left box'>
  <h3><%= t('general.report') %></h3><br>

  <p>
    <strong><%= t('general.subject') %>:</strong>
    <%= @reports.subject %>
  </p>

  <p>
    <strong><%= t('general.description') %>:</strong>
    <%= @reports.description.html_safe %>
  </p>

  <p>
    <strong><%= t('general.reporter') %>:</strong>
    <%= @reports.user.full_name %>
  </p>

  <p>
    <strong><%= t('general.date') %>:</strong>
    <%= display_date(@reports.created_at) %>
  </p>

  <p>
    <strong><%= t('general.state') %></strong>
    <%= @reports.address %>
  </p>
  <% if admin? %>
      <p><%= link_to t('general.edit'), edit_report_path(@reports) %> |
        <%= link_to t('general.destroy'), @reports, :confirm => 'Are you sure?', :method => :delete %> |
  <% end %>
  <%= link_to t('general.view'), reports_path %> |
  <%= link_to 'Поддержать ', vote_up_report_path(@reports), :remote => true, :method => :post, :title => "Нажмите чтобы проголосовать!" %>
  <span class="vote-count"><%= @reports.votes_count %></span></p>

  <%= raw(disqus_thread) %>
</div>
<div id="sidebar" class="col-right">
  <div class='widget'>
    <div class="static_map widget"></div>
  </div>

  <script type="text/javascript">
      var arr = <%= @reports.to_json(:only => [:coordinates, :id, :image_file_name], :include => :assets).html_safe %>;
      var latLng = arr['report']['coordinates'];

      $(document).ready(function() {

          $('.static_map').html("<img src='http://maps.google.com/maps/api/staticmap?center=" + latLng + "&zoom=15&size=306x238&&markers=color:blue|label:P|" + latLng + "&sensor=false'/>");

          if (!arr['report']['assets'].length == 0) {
              for (var i = 0; i < arr['report']['assets'].length; i++) {
                  var image_id = arr['report']['assets'][i]['id'];
                  var image_name = arr['report']['assets'][i]['image_file_name'];

                  $('#slider ul').each(function() {
                      $(this).append("<li><img style='width:302px; margin:2px;' src='/system/images/" + image_id + "/thumb/" + image_name + "'/></li>")
                  });
              }

              $("#slider").easySlider({
                  auto: true,
                  continuous: true,
                  prevText : 'Предыдущий ',
                  nextText : 'Следующий'
              });
          } else {
              $('#attached_images').remove();
          }
      });
  </script>
  <div class="widget" id="attached_images">
    <strong><%= t('general.photo') %>: </strong>

    <div class="images_widget widget">
      <div class="thumbnail" id="slider">
        <ul></ul>
      </div>
    </div>
  </div>
</div>

app/views/reports/show.js.erb
var vote = $(".vote-count");
$(vote).html(<%= @reports.votes_count %>);

<% unless (user_signed_in?) %>
   $(vote).html('| Зарегистрироваться чтобы проголосовать');
<% end %>