config/routes.rb
Monica::Application.routes.draw do

  resources :articles

  root :to => "homes#index"
  resources :reports
  match "about" => "articles#about"
  match "contacts" => "articles#contact"
  
  resources :reports do
    member do
      post :vote_up
    end
  end
  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}
  match "/auth/:provider/callback" => "authentications#create"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_footer.html.erb
<div class="clear-block"></div>
<div id="footer" class="col-full">

  <div class="top">
    <div id="widget-left" class="col-left">
    </div>

    <div id="widget-right" class="col-right">
    </div>

    <div class="fix"></div>
  </div>

  <div class="bottom">

    <div id="copyright" class="col-left">
      <p>© 2011 All Rights Reserved.</p>
    </div>

    <div id="credit" class="col-right">
      <p>Developed by&nbsp;
        <a href="http://im.kg">IM.KG</a>
      </p>

    </div>

  </div>
</div>

app/views/layouts/_header.html.erb
<%= javascript_include_tag "jquery.simplemodal", "init" %>

<div id="header" class="col-full">
  <div id="logo">

    <a href="http://point.kg/" title="Ещё один сайт на Munik"><h1>POINT.KG</h1></a>

    <h1 class="site-title"><a href="http://localhost/wordpress">Delegate</a></h1>
    <span class="site-description">Ещё один сайт на Munik</span>

  </div>
  <div id="lang">
    <%= language_selector %>
  </div>
</div>


<div id="navigation" class="col-full">
  <ul id="nav" class="fl sf-js-enabled sf-shadow">
    <li><%= link_to t('general.home'), root_path %></li>
    <li><%= link_to t('general.report_prob'), new_report_path %></li>
    <li><%= link_to t('general.recent_reports'), reports_path %></li>
    <li><%= link_to t('general.about'), about_url %></li>
    <li><%= link_to t('general.contact'), contacts_url %></li>
  </ul>

  <div id="user_nav">
    <% if user_signed_in? %>
        <%= current_user.name %>
        <%= link_to t('general.sign_out'), destroy_user_session_path %>
        <% if admin? %>
            <%= link_to " | Admin", rails_admin_dashboard_url %>
        <% end %>
    <% else %>
        <%= link_to t('general.registration'), new_user_registration_path %>
        |  <%= link_to t('general.sign_in'), new_user_session_path, :id => "login_link"  %>
    <% end %>
  </div>
  <div id="overlay-content" style="display:none">
    <%= render "sessions/form" %>
  </div>
</div>

app/views/layouts/_stylesheets.html.erb
  <!--[if IE 6]>
  <script type="text/javascript" src="http://localhost/wordpress/wp-content/themes/delegate/includes/js/pngfix.js"></script>
  <script type="text/javascript" src="http://localhost/wordpress/wp-content/themes/delegate/includes/js/menu.js"></script>
  <link rel="stylesheet" type="text/css" media="all" href="http://localhost/wordpress/wp-content/themes/delegate/css/ie6.css" />
  <![endif]-->

  <!--[if IE 7]>
  <link rel="stylesheet" type="text/css" media="all" href="http://localhost/wordpress/wp-content/themes/delegate/css/ie7.css" />
  <![endif]-->

  <!--[if IE 8]>
  <link rel="stylesheet" type="text/css" media="all" href="http://localhost/wordpress/wp-content/themes/delegate/css/ie8.css" />
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Municipality <%= @page_title %> </title>

  <%= javascript_include_tag 'jquery-1.4.2.min', 'rails', 'application', 'highcharts', 'init' %>
  <%= stylesheet_link_tag 'style', :media => 'screen' %>
  <%= stylesheet_link_tag 'effects', 'default', 'custom', 'reset', 'form', :media => 'all' %>
  <%# include_tiny_mce_if_needed %>
  <%= csrf_meta_tag %>
  <%= yield(:head) %>

</head>

<body>
  
<div id="container">
  <%= render "layouts/header" %>
  <div id="content" class="col-full">
    <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <%= content_tag :h1, yield(:title) if show_title? %>
    <%= yield %>
  </div>
  <%= render('layouts/footer') %>
</div>

</body>
</html>